
CREATE TABLE hhi -- FROM TOOL
(
`a` VARCHAR(7),
`b` VARCHAR(2),
`c` VARCHAR(15),
`d` VARCHAR(27),
`e` VARCHAR(1),
`f` VARCHAR(14),
`g` VARCHAR(14),
`h` VARCHAR(13),
`i` VARCHAR(3),
`j` VARCHAR(8),
`k` VARCHAR(8),
`l` VARCHAR(6),
`m` VARCHAR(9),
`n` VARCHAR(1),
`o` VARCHAR(103),
`p` VARCHAR(1),
`q` VARCHAR(1),
`r` VARCHAR(1),
`s` VARCHAR(3),
`t` VARCHAR(2),
`u` VARCHAR(24),
`v` VARCHAR(1),
`w` VARCHAR(3)
);

TRUNCATE hhi;

SHOW VARIABLES;

SELECT * FROM hhi;